name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-flask
        
    - name: Test with pytest
      run: |
        pytest -v
        
  # Simplificando o deploy para usar apenas o GitHub Pages temporariamente
  # para demonstração, já que não temos as secrets do GCP configuradas
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Create demo static site
      run: |
        mkdir -p demo_site
        echo "<html><head><title>DocJur - Sistema de Gestão Documental Jurídica</title></head>" > demo_site/index.html
        echo "<body><h1>DocJur - Sistema de Gestão Documental Jurídica</h1>" >> demo_site/index.html
        echo "<p>Deploy de demonstração realizado com sucesso!</p>" >> demo_site/index.html
        echo "<p>Esta é uma versão de demonstração do sistema.</p>" >> demo_site/index.html
        echo "</body></html>" >> demo_site/index.html
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: demo_site
